### ISSUE TITLE
Godot 4

### ISSUE THREAD

**Issue by github-cyprien** [GDWired/GDPaho#1]
Hi !
Thank you for this work ! Do you plan to port this library to Godot 4 ? Do you think it's a big work ?
Thanks !!

**Comment by jferdelyi** [comment]
Hello, sorry for the delay, I was sure I'd written an answer ^^'. I'm going to create a version of Godot 4 soon, I'm waiting a bit to be sure that GDExtension (the new version of GDNative in short) is stable!

**Comment by jferdelyi** [comment]
Update, I have pushed a quick iteration for Godot 4 :) https://github.com/GDWired/GDPaho/tree/godot-4
There is a bug with UTF8 encoding, but everything seems to work as Godot 3.5

**Comment by github-cyprien** [comment]
Thank you ! I will test it soon !
I would like to make a video for my youtube channel with mqtt : https://www.youtube.com/watch?v=4q55j83gi24

**Comment by jferdelyi** [comment]
Ho ok cool :) don’t forget to tell me when the video is online ;)

**Comment by jferdelyi** [comment]
EDIT: I've compiled and successfully run the plugin on macOS and Windows, not yet tested on Linux.
On Windows using cmake, and scons on macOS, in the end it should work using cmake for all platforms!

**Comment by github-cyprien** [comment]
I'm on linux, i will try to test it this week. Could you tell me what is the difference with this project ? https://godotengine.org/asset-library/asset/1993

**Comment by jferdelyi** [comment]
The main difference is : my plugin is developed in C/C++ and the other one in GDScript purely 
My plugin should be faster but I never tested it, and also Paho (the library used on my plugin) is widely tested.

Linux build seems ok now

**Comment by github-cyprien** [comment]
Ok Thanks for your work !

**Comment by jferdelyi** [comment]
You're welcome, when GDPaho version 4.1 is stable, I'll publish it on the Godot store (for versions 3.5 and 4.1). 
If you need a ready-to-run project for testing, I can provide you with the demo project with the compiled plugin?

**Comment by jferdelyi** [comment]
The godot4 branch runs on Linux, macOS and Linux!
